export const MODEL_MEMORY_PLUGIN_ID = "model-memory";
export const LIVE_MODEL_MEMORY_ENABLED_ENV = "MODEL_MEMORY_LIVE_ENABLED";
export const MODEL_MEMORY_PROJECTION_ARTIFACTS_ENABLED_ENV =
  "MODEL_MEMORY_PROJECTION_ARTIFACTS_ENABLED";
export const MODEL_MEMORY_BOOTSTRAP_OVERLAY_ENABLED_ENV = "MODEL_MEMORY_BOOTSTRAP_OVERLAY_ENABLED";
export const MODEL_MEMORY_TOOL_RESULT_PROOF_CAPTURE_ENABLED_ENV =
  "MODEL_MEMORY_TOOL_RESULT_PROOF_CAPTURE_ENABLED";
export const DEFAULT_STRICT_MMV2_MODEL_REF = "openai-codex/gpt-5.4-mini";
export const MODEL_MEMORY_STRICT_CAPTURE_MODEL_ID_ENV = "MODEL_MEMORY_STRICT_CAPTURE_MODEL_ID";
export const MODEL_MEMORY_STRICT_CANDIDATE_MODEL_ID_ENV = "MODEL_MEMORY_STRICT_CANDIDATE_MODEL_ID";
export const MODEL_MEMORY_RETRIEVAL_MODEL_ID_ENV = "MODEL_MEMORY_RETRIEVAL_MODEL_ID";
export const MODEL_MEMORY_CONTEXT_PATH_PREFIX = ".openclaw/model-memory/context";
export const MODEL_MEMORY_RETRIEVAL_CONTEXT_PATH = `${MODEL_MEMORY_CONTEXT_PATH_PREFIX}/retrieval-pack.md`;
export const BOOTSTRAP_PROJECTION_TARGET_IDS = new Set(["memory-md", "user-md"]);
