export type RuntimeWorkGraphSchedulerSnapshotSummary = {
  workflowId: string;
  rootRuntimeJobId?: string | null;
  graphStatus: string;
  nodeSummaries: Array<{
    nodeId: string;
    nodeKind: string;
    assignedRole: string;
    nodeStatus: string;
    capabilityId?: string | null;
    metadataCapabilityId?: string | null;
    executorKey?: string | null;
    commitmentIdsAdvanced?: string[];
    downstreamConsumer?: string | null;
    inputHandoffRefs?: string[];
    targetRefs?: string[];
    sourceMaterialRequirementKinds?: string[];
    sourceRequirementRef?: string | null;
    executionIntent?: string | null;
    evidenceMode?: string[];
    contextQuestions?: string[];
    resourceObjectiveFocusStatus?: string | null;
    resourceObjectiveFocusRef?: string | null;
    resourceObjectiveFocusLegalRefUniverseRef?: string | null;
    resourceObjectiveFocusAllowedToolIds?: string[];
    resourceObjectiveFocusRequiredFields?: string[];
    resourceObjectiveFocusLegalHandles?: Array<{
      handle: string;
      kind: string;
      ref: string;
      boundedLabel: string;
    }>;
    sourceMaterialRequirementRefs?: string[];
    contextSnapshotRefs?: string[];
    acceptedSourceMaterialRefs?: string[];
    missingSourceMaterialRequirementRefs?: string[];
    missingResourceHandoffRefs?: string[];
    failedResourceFulfillmentNodeIds?: string[];
    pendingResourceFulfillmentNodeIds?: string[];
    contextLimitationWaiverRefs?: string[];
    noContextNeededRationale?: string | null;
    outputArtifactRefs: string[];
    lastStatusReasonCodes?: string[];
    lastRepairClassificationRef?: string | null;
    lastRepairFailureClass?: string | null;
    lastRepairStrategy?: string | null;
    lastRepairBoundary?: string | null;
    highCapabilityEscalationRequired?: boolean;
  }>;
  edgeSummaries?: Array<{
    edgeId: string;
    fromNodeId: string | null;
    toNodeId: string | null;
    edgeKind: string;
  }>;
  edgeCount: number;
  humanTaskCount: number;
  latestCheckpointKinds: string[];
};
