import type { JsonValue } from "../runtime-job-repository.ts";
import type { RuntimeEvidenceKind } from "./runtime-evidence-kind.ts";
import type { RuntimeValidationPhase } from "./validation-phase.ts";

export type CommitmentEvidenceClaim = {
  commitmentId: string;
  evidenceRef: string;
  evidenceKind: RuntimeEvidenceKind;
  claimSummary: string;
  limitations: string[];
  validationPhase?: RuntimeValidationPhase;
  validationRefs?: string[];
  changedFileRefs?: string[];
  validationPhaseCompatibility?: "compatible" | "incompatible" | "not_closure_capable";
  validationPhaseReasonCodes?: string[];
  rawPromptStored: false;
  rawResponseStored: false;
  rawProviderLogStored: false;
};

export type RuntimeWorkGraphNodeExecutionResult = {
  status: "succeeded" | "needs_review" | "failed" | "blocked" | "waiting_for_human" | "canceled";
  outputArtifactRefs: string[];
  producedOutputRefs?: string[];
  artifactRefs?: string[];
  modelRunRefs?: string[];
  runtimeToolInvocationRefs?: string[];
  scriptJobRefs?: string[];
  dbOperationRefs?: string[];
  validationRefs?: string[];
  validationSummaryRefs?: string[];
  changedFileRefs?: string[];
  humanDecisionRefs?: string[];
  closeoutRefs?: string[];
  limitations?: string[];
  sufficiencyJudgmentRef?: string | null;
  ownerSummary?: string | null;
  eli5Summary?: string | null;
  reasonCodes: string[];
  evidenceClaims?: CommitmentEvidenceClaim[];
  metadata?: JsonValue;
  rawPromptStored: false;
  rawResponseStored: false;
  rawProviderLogStored: false;
  rawToolLogStored?: false;
  rawDbRowsStored?: false;
  authorityGranted?: false;
  controlsApplied?: false;
  workQueueLifecycleMutated: false;
  runtimeLifecycleMutated?: false;
};
