import { describe, expect, it } from "vitest";
import { buildLatestRunState } from "./latest-run-state.ts";

describe("latest run state", () => {
  it("builds a compact compaction-safe operator state without raw storage", () => {
    const state = buildLatestRunState({
      runtimeJobId: "job-1",
      workItemId: "work-1",
      promptHash: "sha256:prompt",
      promptRef: "source-prompt://prompt",
      promptLength: 12_345,
      processRunning: false,
      terminalStatus: "needs_review",
      adapterTerminalStatus: "needs_review",
      retryState: "retry_scheduled",
      runtimeJob: {
        state: "pending",
        attempts: 1,
        maxAttempts: 2,
        workerId: null,
        startedAt: "2026-05-20T00:00:00.000Z",
        completedAt: null,
      },
      graphId: "graph-1",
      latestProgress: {
        stage: "node_agent_session",
        currentPhase: "domain_action_gate_blocked",
        schedulerPhase: "node_worker_prompt_missing_source_material",
        nodeId: "node-1",
        activeNodeKind: "implementation_scoped",
        workIntentId: "work-intent-1",
        workIntentTitle: "Patch Product/Spec wiring",
        executionIntent: "source_edit",
        evidenceMode: ["changed_file_evidence", "validation_evidence"],
        selectedCapabilityId: "implementation.kimi.scoped_patch",
        executorKey: "kind:implementation",
        workerRef: "worker://kimi/patch",
        schedulerToolId: "worker.invoke",
        nodeLifecycleProjectionRef: "node-lifecycle-projection://impl-1",
        nodeLifecycleProjectionGate: "node_agent_session_ready",
        nodeLifecycleProjectionStatus: "ready",
        roleId: "implementation_engineer",
        modelRef: "openai-codex/gpt-5.5",
        providerPath: "codex_app_server",
        currentObjective: "Hydrate write authority for the node-local edit lane.",
        blockerSummary: "target snapshot missing",
        nextDecisionNeeded: "hydrate_action_gate",
        eli5Progress:
          "OpenClaw has the node-local context ledger, but the edit gate still needs target snapshots.",
        reasonCodes: ["action_gate_target_snapshot_missing"],
        artifactRefs: [
          "runtime-job://job-1/node-resource-demand/session/impl-1",
          "runtime-job://job-1/node-resource-ledger/impl-1/manifest",
        ],
        parallelFrontier: {
          currentSuperstep: 3,
          selectedNodeIds: ["impl-1"],
          runningNodeIds: ["impl-1"],
          blockedNodeIds: ["impl-2"],
          branchResults: [
            {
              branchId: "branch-1",
              nodeId: "impl-1",
              nodeKind: "implementation_scoped",
              capabilityId: "implementation.kimi.scoped_patch",
              targetCommitmentIds: ["C1"],
              status: "running",
              evidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
              nextTransition: "evaluate_downstream",
              reasonCodes: ["frontier_node_running"],
            },
            {
              branchId: "branch-2",
              nodeId: "impl-2",
              nodeKind: "implementation_scoped",
              capabilityId: "implementation.qwen.scoped_patch",
              targetCommitmentIds: ["C2"],
              status: "blocked",
              failureClass: "node_worker_prompt_authoring_blocked",
              errorPath: "nodeAgentWorkerPrompt.sourceMaterial",
              blockerSummary: "worker prompt missing source material",
              repairAction: "node.agent_session.invoke",
              nextTransition: "node.agent_session.invoke",
              nodeLifecycleProjectionRef: "node-lifecycle-projection://impl-2",
              reasonCodes: ["target_snapshot_missing"],
            },
          ],
        },
        branchScopedFrontierStates: [
          {
            artifactKind: "runtime_work_graph_branch_scoped_frontier_state",
            schemaVersion: "execution-platform.runtime-work-graph.branch-scoped-frontier.v1",
            graphId: "graph-1",
            currentSuperstep: 3,
            branchId: "branch-1",
            parentBranchId: null,
            nodeId: "impl-1",
            nodeKind: "implementation_scoped",
            workIntentRef: "work-intent://1",
            contractRef: "runtime-job://job-1/contract/impl-1",
            readinessRef: "runtime-job://job-1/readiness/impl-1",
            sourceMaterialRequirementRefs: ["source-material-requirement://impl-1"],
            sourceMaterialPacketRef: "source-material-packet://impl-1",
            sourceMaterialRef: "source-material-packet://impl-1",
            status: "running",
            blocker: null,
            blockerSignature: null,
            consumerRefs: ["validation-1"],
            dependentConsumers: ["validation-1"],
            siblingBranchIds: ["branch-2"],
            successfulEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
            failedEvidenceRefs: [],
            repairNodeRefs: [],
            diagnosticOnlyNodeRefs: [],
            nextLegalTransitions: ["evaluate_downstream"],
            capabilityId: "implementation.kimi.scoped_patch",
            executorKey: "kind:implementation",
            modelRef: "moonshotai/kimi-k2.6",
            workerRef: "worker://kimi/patch",
            phase: "execute_node",
            objectiveSummary: "Patch Product/Spec wiring",
            whySelected: "Independent source edit branch.",
            currentToolId: "worker.invoke",
            currentToolInvocationRef: "runtime-tool://worker.invoke/impl-1",
            targetRefSummary: ["src/impl-1.ts"],
            readinessStatus: "executable",
            rootCauseRef: null,
            rootCauseSystemic: null,
            updatedAt: "2026-05-20T00:00:00.000Z",
            rawPromptStored: false,
            rawResponseStored: false,
            rawProviderLogStored: false,
            rawToolLogStored: false,
            rawDbRowsStored: false,
            secretsStored: false,
          },
          {
            artifactKind: "runtime_work_graph_branch_scoped_frontier_state",
            schemaVersion: "execution-platform.runtime-work-graph.branch-scoped-frontier.v1",
            graphId: "graph-1",
            currentSuperstep: 3,
            branchId: "branch-2",
            parentBranchId: null,
            nodeId: "impl-2",
            nodeKind: "implementation_scoped",
            workIntentRef: "work-intent://2",
            contractRef: "runtime-job://job-1/contract/impl-2",
            nodeLifecycleProjectionRef: "node-lifecycle-projection://impl-2",
            sourceMaterialRequirementRefs: ["source-material-requirement://impl-2"],
            sourceMaterialPacketRef: null,
            sourceMaterialRef: null,
            status: "blocked",
            blocker: {
              code: "node_worker_prompt_missing_source_material",
              summary: "worker prompt missing source material",
              schemaPath: "nodeAgentWorkerPrompt.sourceMaterial",
              policyPath: null,
              reasonCodes: ["target_snapshot_missing"],
            },
            blockerSignature: "blocker-sig-2",
            consumerRefs: ["validation-2"],
            dependentConsumers: ["validation-2"],
            siblingBranchIds: ["branch-1"],
            successfulEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
            failedEvidenceRefs: [],
            repairNodeRefs: ["runtime-work-graph://node/repair-impl-2"],
            diagnosticOnlyNodeRefs: ["runtime-work-graph://node/diag-impl-2"],
            nextLegalTransitions: ["node.agent_session.invoke"],
            capabilityId: "implementation.qwen.scoped_patch",
            executorKey: "kind:implementation",
            modelRef: "qwen/qwen3-coder-next",
            workerRef: "worker://qwen/patch",
            phase: "resources_required",
            objectiveSummary: "Patch blocked branch.",
            whySelected: "Sibling branch needs materialization.",
            currentToolId: "node.compile_execution_packet",
            currentToolInvocationRef: "runtime-tool://node.compile_execution_packet/impl-2",
            targetRefSummary: ["src/impl-2.ts"],
            readinessStatus: "resources_required",
            rootCauseRef: "runtime-work-graph://frontier-root-cause/graph-1/sig-1/repeat/2",
            rootCauseSystemic: true,
            updatedAt: "2026-05-20T00:00:00.000Z",
            rawPromptStored: false,
            rawResponseStored: false,
            rawProviderLogStored: false,
            rawToolLogStored: false,
            rawDbRowsStored: false,
            secretsStored: false,
          },
        ],
        schedulerFrontierState: {
          currentSuperstep: 3,
          selectedExecutableNodeIds: ["impl-1"],
          blockedFrontierNodeIds: ["impl-2"],
          openCommitmentIds: ["C1", "C2"],
          nextLegalTransition: "execute_frontier",
        },
        schedulerModelCallEnvelope: {
          artifactKind: "runtime_work_graph_scheduler_model_call_envelope",
          schemaVersion: "execution-platform.runtime-work-graph.scheduler-model-call-envelope.v1",
          envelopeId: "graph-1:scheduler:3",
          envelopeRef: "runtime-work-graph://scheduler-model-call-envelope/graph-1%3A3",
          phase: "rejection",
          decisionSlot: "scheduler.select_next_action",
          schedulerPhase: "scheduler_decision_rejected",
          modelRef: "openai-codex/gpt-5.5",
          providerPath: "codex_app_server",
          providerProfileId: "codex_app_server",
          modelTaskClass: "global_reasoning",
          modelPolicyRef: "model-task-policy://global_reasoning/default",
          contractBoundaryId: "scheduler_global_reasoning",
          modelPolicyBindingRef: "model-contract-boundary://scheduler_global_reasoning",
          reasoningMode: "high",
          parserMode: "json_object",
          proofCleanlinessState: "clean",
          inputByteCount: 42_000,
          graphNodeCount: 12,
          graphEdgeCount: 18,
          activeFrontierCounts: {
            ready: 1,
            blocked: 1,
          },
          rejectedToolCallSummary: {
            status: "rejected",
            reasonCodes: ["target_snapshot_missing"],
          },
          schemaErrorPath: "nodeExecutionSnapshot.contextRefs",
          repairFieldHints: ["nodeExecutionSnapshot.contextRefs"],
          missingFields: ["nodeExecutionSnapshotRef"],
          reasonCodes: ["target_snapshot_missing"],
          rawPromptStored: false,
          rawResponseStored: false,
          rawProviderLogStored: false,
          rawToolLogStored: false,
          rawCommandLogStored: false,
          rawDbRowsStored: false,
          hiddenReasoningStored: false,
          secretsStored: false,
        },
        noProgressSignature: {
          signatureHash: "sig-1",
          terminalBlockerCode: "frontier_blocked",
          blockerReasonCodes: ["target_snapshot_missing"],
        },
        frontierRootCauseArtifact: {
          artifactKind: "runtime_work_graph_frontier_root_cause",
          signatureHash: "sig-1",
          repeatCount: 2,
          systemic: true,
          recommendedRepairBoundary: "node_agent_session_resume",
          affectedNodeIds: ["impl-2"],
          affectedBranchIds: ["branch-2"],
          successfulSiblingEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
          missingFields: ["nodeExecutionSnapshotRef"],
          schemaErrorPaths: ["nodeExecutionSnapshot.contextRefs"],
          policyErrorPaths: [],
          contractRefs: ["runtime-job://job-1/contract/impl-2"],
          sourceMaterialPacketKinds: ["node_execution_source_material"],
          providerProfileIds: [],
          nextLegalTransitions: ["node.agent_session.invoke"],
          reasonCodes: ["target_snapshot_missing"],
        },
        noProgressRepeatCount: 2,
        missionLedgerEvaluationThrottle: {
          nodeId: "impl-2",
          shouldEvaluate: false,
          reasonCodes: ["node_has_no_new_evidence"],
        },
        expansionAdmissionDecisionRef:
          "runtime-work-graph://expansion-admission/graph-1/3/admission",
        expansionAdmissionPolicyRef: "runtime-work-graph.expansion-admission.v1",
        expansionAdmissionStatus: "accepted_paged",
        expansionAdmissionOriginalNodeCount: 12,
        expansionAdmissionOriginalEdgeCount: 18,
        expansionAdmissionAdmittedNodeCount: 4,
        expansionAdmissionAdmittedEdgeCount: 6,
        expansionAdmissionDeferredNodeCount: 8,
        expansionAdmissionDeferredEdgeCount: 12,
        expansionAdmissionReadyFrontierNodeIds: ["impl-1"],
        expansionAdmissionAdmittedNodeIds: ["impl-1", "impl-2"],
        expansionAdmissionDeferredNodeIds: ["impl-3"],
        expansionAdmissionNextTransition: "persist_admitted_page",
        expansionAdmissionPrerequisiteCritical: false,
        expansionAdmissionReasonCodes: ["expansion_accepted_paged"],
        heapPhaseSnapshots: [
          {
            snapshotRef: "heap-phase://job-1/action-gate-blocked",
            phase: "domain_action_gate_blocked",
            gateKind: "domain_action_gate_blocked",
            graphId: "graph-1",
            nodeId: "impl-2",
            heapUsedBytes: 50_000_000,
            heapTotalBytes: 100_000_000,
            rssBytes: 140_000_000,
            externalBytes: 1_000_000,
            arrayBuffersBytes: 500_000,
            graphNodeCount: 12,
            graphEdgeCount: 18,
            activeBranchCount: 2,
            largestMetadataBytes: 19_000,
            largestMetadataRef: "runtime-job://job-1/latest-run-state",
            largestArtifactBodyBytes: 120_000,
            largestArtifactBodyRef: "artifact://execution-platform/proof-source",
            latestRunStateMetadataBytes: 19_000,
            schedulerProgressMetadataBytes: 16_000,
            workQueueProjectionMetadataBytes: 12_000,
            providerRequestByteCount: 42_000,
            reasonCodes: ["heap_phase_snapshot_recorded"],
            rawPromptStored: false,
            rawResponseStored: false,
            rawProviderLogStored: false,
            rawToolLogStored: false,
            rawCommandLogStored: false,
            rawDbRowsStored: false,
            secretsStored: false,
          },
        ],
      },
      totalWallMs: 123_456,
      phaseWallClock: [{ phase: "node_agent_session", wallMs: 1000 }],
      modelUsageByModel: [{ modelRef: "openai-codex/gpt-5.5", usageKind: "estimated" }],
      missingUsageEventCount: 1,
      usageUnavailableReasons: [{ reason: "codex_app_server_usage_not_returned", count: 1 }],
      recommendedOperatorAction: "Replay from the node-agent session boundary.",
    });

    expect(state).toMatchObject({
      artifactKind: "execution_platform_latest_run_state",
      runtimeJobId: "job-1",
      process: {
        isRunning: false,
        terminalStatus: "needs_review",
        adapterTerminalStatus: "needs_review",
        retryState: "retry_scheduled",
      },
      current: {
        phase: "domain_action_gate_blocked",
        nodeId: "node-1",
        nodeKind: "implementation_scoped",
        workIntentId: "work-intent-1",
        executionIntent: "source_edit",
        evidenceMode: ["changed_file_evidence", "validation_evidence"],
        capabilityId: "implementation.kimi.scoped_patch",
        executorKey: "kind:implementation",
        workerRef: "worker://kimi/patch",
        activeToolId: "worker.invoke",
        nodeLifecycleProjectionRef: "node-lifecycle-projection://impl-1",
        nodeLifecycleProjectionGate: "node_agent_session_ready",
        nodeLifecycleProjectionStatus: "ready",
        blockerSummary: "target snapshot missing",
      },
      activeFrontier: {
        state: "present",
        status: "terminal",
        graphId: "graph-1",
        selectedNodeIds: ["impl-1"],
        blockedNodeIds: ["impl-2"],
        nextTransition: "run_frontier",
        noProgress: {
          state: "present",
          repeatCount: 2,
          terminalBlockerCode: "frontier_blocked",
        },
        rootCause: {
          state: "present",
          signatureHash: "sig-1",
          recommendedRepairBoundary: "node_agent_session_resume",
          affectedNodeIds: ["impl-2"],
          successfulSiblingEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
        },
        missionLedgerEvaluationThrottle: {
          state: "present",
          nodeId: "impl-2",
          shouldEvaluate: false,
        },
      },
      canonicalReadbackGate: {
        state: "present",
        gateKind: "terminal_needs_review",
        gateStatus: "terminal",
        confidence: "canonical",
        sourceKind: "terminal_outcome",
        nodeId: "impl-2",
        branchId: "branch-2",
        contractRef: "runtime-job://job-1/contract/impl-2",
        nodeLifecycleProjectionRef: "node-lifecycle-projection://impl-2",
        nodeLifecycleProjectionGate: "node_agent_session_ready",
        schemaPath: "nodeAgentWorkerPrompt.sourceMaterial",
        nextLegalTransition: "node.agent_session.invoke",
        successfulSiblingEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
        rawPromptStored: false,
        rawResponseStored: false,
        rawProviderLogStored: false,
      },
      rawPromptStored: false,
      rawResponseStored: false,
      rawProviderLogStored: false,
      rawToolLogStored: false,
      rawDbRowsStored: false,
      secretsStored: false,
    });
    expect(state.proofEnvironment).toMatchObject({
      state: "present",
      largestMetadataBytes: 19_000,
      largestMetadataRef: "runtime-job://job-1/latest-run-state",
      largestArtifactBodyBytes: 120_000,
      largestArtifactBodyRef: "artifact://execution-platform/proof-source",
      latestRunStateMetadataBytes: 19_000,
      schedulerProgressMetadataBytes: 16_000,
      workQueueProjectionMetadataBytes: 12_000,
      providerRequestMaxBytes: 42_000,
      reasonCodes: ["heap_phase_snapshot_recorded"],
      rawPromptStored: false,
      rawResponseStored: false,
      rawProviderLogStored: false,
      rawToolLogStored: false,
      rawDbRowsStored: false,
      secretsStored: false,
    });
    expect(state.expansionAdmission).toMatchObject({
      state: "present",
      status: "accepted_paged",
      originalNodeCount: 12,
      admittedNodeCount: 4,
      deferredNodeCount: 8,
      nextTransition: "persist_admitted_page",
      prerequisiteCritical: false,
      readyFrontierNodeIds: ["impl-1"],
    });
    expect(state.schedulerModelCallEnvelope).toMatchObject({
      phase: "rejection",
      decisionSlot: "scheduler.select_next_action",
      schedulerPhase: "scheduler_decision_rejected",
      inputByteCount: 42_000,
      graphNodeCount: 12,
      contractBoundaryId: "scheduler_global_reasoning",
      modelPolicyBindingRef: "model-contract-boundary://scheduler_global_reasoning",
      proofCleanlinessState: "clean",
      schemaErrorPath: "nodeExecutionSnapshot.contextRefs",
      rawPromptStored: false,
      rawResponseStored: false,
      rawProviderLogStored: false,
      hiddenReasoningStored: false,
    });
    expect(JSON.stringify(state)).not.toContain("boundaryReplay");
    expect(state.activeFrontier.branchStates).toMatchObject([
      {
        branchId: "branch-1",
        nodeId: "impl-1",
        status: "running",
        contractRef: "runtime-job://job-1/contract/impl-1",
        dependentConsumers: ["validation-1"],
      },
      {
        branchId: "branch-2",
        nodeId: "impl-2",
        status: "blocked",
        blockerSchemaPath: "nodeAgentWorkerPrompt.sourceMaterial",
        nextTransition: "node.agent_session.invoke",
        nodeLifecycleProjectionRef: "node-lifecycle-projection://impl-2",
        successfulEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
        repairNodeRefs: ["runtime-work-graph://node/repair-impl-2"],
        diagnosticOnlyNodeRefs: ["runtime-work-graph://node/diag-impl-2"],
      },
    ]);
    expect(JSON.stringify(state)).not.toContain("raw prompt");
  });

  it("keeps native node-agent refs in latest-run-state and canonical gate projection", () => {
    const state = buildLatestRunState({
      runtimeJobId: "job-node-local",
      workItemId: "work-node-local",
      graphId: "graph-node-local",
      processRunning: true,
      latestProgress: {
        currentPhase: "node_worker_prompt_missing_source_material",
        nodeId: "impl-node-local",
        activeNodeKind: "implementation_scoped",
        workIntentId: "work-intent-node-local",
        executionIntent: "source_edit",
        evidenceMode: ["changed_file_evidence"],
        nodeExecutionSnapshotRef:
          "node-execution-snapshot://job-node-local/impl-node-local/attempt-1",
        nodeWorkerPromptRef: "node-agent-worker-prompt://nrun-node-local/abc123",
        nodeWorkerPromptArtifactRef:
          "runtime-job://job-node-local/node-agent-worker-prompt/impl-node-local",
        nodeWorkerPromptHash: "sha256:node-worker-prompt",
        nodeWorkerPromptByteCount: 1234,
        nodeWorkerPromptStatus: "accepted",
        nodeWorkerPromptAuthorModelRunRef: "openrouter-provider-text-turn://kimi/abc123",
        nodeAgentSessionKey: "agent:execution-coding:node:nrun-node-local",
        nodeAgentSessionMessageId:
          "openclaw-session-message://agent%3Aexecution-coding%3Anode%3Anrun-node-local/initial/abc123",
        nodeAgentSessionTranscriptRef:
          "openclaw-session-file://%2Froot%2F.openclaw%2Fsessions%2Fnrun-node-local.jsonl",
        nodeAgentInitialMessageHash: "sha256:node-worker-prompt",
        nodeAgentPromptSessionHashMatch: true,
        nodeAgentStartReceiptRef: "node-agent-start-receipt://nrun-node-local/accepted",
        nodeAgentStartStatus: "accepted",
        nodeAgentStartBlockerKind: null,
        nodeAgentSessionTraceRefs: [
          "runtime-job://job-node-local/node-agent-trace/impl-node-local",
        ],
        nodeFinishArtifactRefs: ["runtime-job://job-node-local/node-finish/impl-node-local"],
        domainResourceSelectionStatus: "blocked",
        domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
        actionGateStatus: "blocked",
        actionGateMissingFields: ["targetFileSnapshots"],
        providerDiagnosticStatus: "available",
        providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
        branchScopedFrontierStates: [
          {
            branchId: "branch-node-local",
            nodeId: "impl-node-local",
            nodeKind: "implementation_scoped",
            workIntentRef: "work-intent://impl-node-local",
            contractRef: "contract://impl-node-local",
            nodeExecutionSnapshotRef:
              "node-execution-snapshot://job-node-local/impl-node-local/attempt-1",
            nodeWorkerPromptRef: "node-agent-worker-prompt://nrun-node-local/abc123",
            nodeWorkerPromptArtifactRef:
              "runtime-job://job-node-local/node-agent-worker-prompt/impl-node-local",
            nodeWorkerPromptHash: "sha256:node-worker-prompt",
            nodeWorkerPromptByteCount: 1234,
            nodeWorkerPromptStatus: "accepted",
            nodeWorkerPromptAuthorModelRunRef: "openrouter-provider-text-turn://kimi/abc123",
            nodeAgentSessionKey: "agent:execution-coding:node:nrun-node-local",
            nodeAgentSessionMessageId:
              "openclaw-session-message://agent%3Aexecution-coding%3Anode%3Anrun-node-local/initial/abc123",
            nodeAgentSessionTranscriptRef:
              "openclaw-session-file://%2Froot%2F.openclaw%2Fsessions%2Fnrun-node-local.jsonl",
            nodeAgentInitialMessageHash: "sha256:node-worker-prompt",
            nodeAgentPromptSessionHashMatch: true,
            nodeAgentStartReceiptRef: "node-agent-start-receipt://nrun-node-local/accepted",
            nodeAgentStartStatus: "accepted",
            nodeAgentStartBlockerKind: null,
            nodeLifecycleProjectionRef: "node-lifecycle-projection://impl-node-local",
            sourceMaterialRequirementRefs: ["source-material-requirement://impl-node-local"],
            nodeAgentSessionTraceRefs: [
              "runtime-job://job-node-local/node-agent-trace/impl-node-local",
            ],
            nodeFinishArtifactRefs: ["runtime-job://job-node-local/node-finish/impl-node-local"],
            domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
            domainResourceSelectionStatus: "blocked",
            actionGateStatus: "blocked",
            actionGateMissingFields: ["targetFileSnapshots"],
            providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
            providerDiagnosticStatus: "available",
            status: "blocked",
            nodeLifecycleProjectionGate: "node_agent_session_ready",
            nodeLifecycleProjectionStatus: "blocked",
            phase: "node_agent_session_ready",
            blocker: {
              code: "node_worker_prompt_missing_source_material",
              summary: "node worker prompt needs source material",
              schemaPath: "nodeAgentWorkerPrompt.sourceMaterial",
              reasonCodes: ["node_worker_prompt_missing_source_material"],
            },
            nextLegalTransitions: ["start_node_agent_session"],
          },
        ],
      },
    });

    expect(state.current).toMatchObject({
      nodeExecutionSnapshotRef:
        "node-execution-snapshot://job-node-local/impl-node-local/attempt-1",
      nodeWorkerPromptRef: "node-agent-worker-prompt://nrun-node-local/abc123",
      nodeWorkerPromptArtifactRef:
        "runtime-job://job-node-local/node-agent-worker-prompt/impl-node-local",
      nodeWorkerPromptHash: "sha256:node-worker-prompt",
      nodeWorkerPromptByteCount: 1234,
      nodeWorkerPromptStatus: "accepted",
      nodeWorkerPromptAuthorModelRunRef: "openrouter-provider-text-turn://kimi/abc123",
      nodeAgentSessionKey: "agent:execution-coding:node:nrun-node-local",
      nodeAgentSessionMessageId:
        "openclaw-session-message://agent%3Aexecution-coding%3Anode%3Anrun-node-local/initial/abc123",
      nodeAgentSessionTranscriptRef:
        "openclaw-session-file://%2Froot%2F.openclaw%2Fsessions%2Fnrun-node-local.jsonl",
      nodeAgentInitialMessageHash: "sha256:node-worker-prompt",
      nodeAgentPromptSessionHashMatch: true,
      nodeAgentStartReceiptRef: "node-agent-start-receipt://nrun-node-local/accepted",
      nodeAgentStartStatus: "accepted",
      nodeAgentStartBlockerKind: null,
      nodeAgentSessionTraceRefs: ["runtime-job://job-node-local/node-agent-trace/impl-node-local"],
      nodeAgentFinishArtifactRefs: ["runtime-job://job-node-local/node-finish/impl-node-local"],
      domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
      domainResourceSelectionStatus: "blocked",
      actionGateStatus: "blocked",
      actionGateMissingFields: ["targetFileSnapshots"],
      providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
      providerDiagnosticStatus: "available",
    });
    expect(state.activeFrontier.branchStates[0]).toMatchObject({
      branchId: "branch-node-local",
      nodeWorkerPromptRef: "node-agent-worker-prompt://nrun-node-local/abc123",
      nodeAgentSessionMessageId:
        "openclaw-session-message://agent%3Aexecution-coding%3Anode%3Anrun-node-local/initial/abc123",
      nodeAgentPromptSessionHashMatch: true,
      nodeAgentStartReceiptRef: "node-agent-start-receipt://nrun-node-local/accepted",
      nodeAgentSessionTraceRefs: ["runtime-job://job-node-local/node-agent-trace/impl-node-local"],
      nodeAgentFinishArtifactRefs: ["runtime-job://job-node-local/node-finish/impl-node-local"],
      domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
      actionGateStatus: "blocked",
      providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
    });
    expect(state.canonicalReadbackGate).toMatchObject({
      gateKind: "node_agent_session_ready",
      sourceKind: "branch_scoped_frontier",
      nodeWorkerPromptRef: "node-agent-worker-prompt://nrun-node-local/abc123",
      nodeWorkerPromptArtifactRef:
        "runtime-job://job-node-local/node-agent-worker-prompt/impl-node-local",
      nodeWorkerPromptHash: "sha256:node-worker-prompt",
      nodeWorkerPromptByteCount: 1234,
      nodeWorkerPromptStatus: "accepted",
      nodeWorkerPromptAuthorModelRunRef: "openrouter-provider-text-turn://kimi/abc123",
      nodeAgentSessionKey: "agent:execution-coding:node:nrun-node-local",
      nodeAgentSessionMessageId:
        "openclaw-session-message://agent%3Aexecution-coding%3Anode%3Anrun-node-local/initial/abc123",
      nodeAgentSessionTranscriptRef:
        "openclaw-session-file://%2Froot%2F.openclaw%2Fsessions%2Fnrun-node-local.jsonl",
      nodeAgentInitialMessageHash: "sha256:node-worker-prompt",
      nodeAgentPromptSessionHashMatch: true,
      nodeAgentStartReceiptRef: "node-agent-start-receipt://nrun-node-local/accepted",
      nodeAgentStartStatus: "accepted",
      nodeAgentSessionTraceRefs: ["runtime-job://job-node-local/node-agent-trace/impl-node-local"],
      nodeAgentFinishArtifactRefs: ["runtime-job://job-node-local/node-finish/impl-node-local"],
      domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
      actionGateStatus: "blocked",
      providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
    });
    expect(JSON.stringify(state)).not.toContain("raw prompt");
  });
});
