import { describe, expect, it } from "vitest";
import { buildLatestRunState } from "./latest-run-state.ts";

describe("latest run state", () => {
  it("builds a compact compaction-safe operator state without raw storage", () => {
    const state = buildLatestRunState({
      runtimeJobId: "job-1",
      workItemId: "work-1",
      promptHash: "sha256:prompt",
      promptRef: "source-prompt://prompt",
      promptLength: 12_345,
      processRunning: false,
      terminalStatus: "needs_review",
      adapterTerminalStatus: "needs_review",
      retryState: "retry_scheduled",
      runtimeJob: {
        state: "pending",
        attempts: 1,
        maxAttempts: 2,
        workerId: null,
        startedAt: "2026-05-20T00:00:00.000Z",
        completedAt: null,
      },
      graphId: "graph-1",
      latestProgress: {
        stage: "node_local_node_resource_demand",
        currentPhase: "domain_action_gate_blocked",
        schedulerPhase: "node_local_node_resource_demand_needs_target_snapshot",
        nodeId: "node-1",
        activeNodeKind: "implementation_scoped",
        workIntentId: "work-intent-1",
        workIntentTitle: "Patch Product/Spec wiring",
        executionIntent: "source_edit",
        evidenceMode: ["changed_file_evidence", "validation_evidence"],
        selectedCapabilityId: "implementation.kimi.scoped_patch",
        executorKey: "kind:implementation",
        workerRef: "worker://kimi/patch",
        schedulerToolId: "worker.invoke",
        nodeReadinessStateRef: "runtime-job://job-1/readiness/impl-1",
        nodeReadinessStatus: "ready",
        roleId: "implementation_engineer",
        modelRef: "openai-codex/gpt-5.5",
        providerPath: "codex_app_server",
        currentObjective: "Hydrate write authority for the node-local edit lane.",
        blockerSummary: "target snapshot missing",
        nextDecisionNeeded: "hydrate_action_gate",
        eli5Progress: "OpenClaw has the node-local context ledger, but the edit gate still needs target snapshots.",
        reasonCodes: ["action_gate_target_snapshot_missing"],
        artifactRefs: [
          "runtime-job://job-1/node-resource-demand/session/impl-1",
          "runtime-job://job-1/node-resource-ledger/impl-1/manifest",
        ],
        parallelFrontier: {
          currentSuperstep: 3,
          selectedNodeIds: ["impl-1"],
          runningNodeIds: ["impl-1"],
          blockedNodeIds: ["impl-2"],
          branchResults: [
            {
              branchId: "branch-1",
              nodeId: "impl-1",
              nodeKind: "implementation_scoped",
              capabilityId: "implementation.kimi.scoped_patch",
              targetCommitmentIds: ["C1"],
              status: "running",
              evidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
              nextTransition: "evaluate_downstream",
              reasonCodes: ["frontier_node_running"],
            },
            {
              branchId: "branch-2",
              nodeId: "impl-2",
              nodeKind: "implementation_scoped",
              capabilityId: "implementation.qwen.scoped_patch",
              targetCommitmentIds: ["C2"],
              status: "blocked",
              failureClass: "resource_materialization",
              errorPath: "nodeReadinessState.snapshotStatus",
              blockerSummary: "target snapshot missing",
              repairAction: "materialize_target_snapshot",
              nextTransition: "materialize_resources_or_split_task",
              readinessStateRef: "runtime-job://job-1/readiness/impl-2",
              reasonCodes: ["target_snapshot_missing"],
            },
          ],
        },
        branchScopedFrontierStates: [
          {
            artifactKind: "runtime_work_graph_branch_scoped_frontier_state",
            schemaVersion: "execution-platform.runtime-work-graph.branch-scoped-frontier.v1",
            graphId: "graph-1",
            currentSuperstep: 3,
            branchId: "branch-1",
            parentBranchId: null,
            nodeId: "impl-1",
            nodeKind: "implementation_scoped",
            workIntentRef: "work-intent://1",
            contractRef: "runtime-job://job-1/contract/impl-1",
            readinessRef: "runtime-job://job-1/readiness/impl-1",
            resourceRequirementRefs: ["resource-requirement://impl-1"],
            domainResourcePacketRef: "resource-packet://impl-1",
            resourcePacketRef: "resource-packet://impl-1",
            status: "running",
            blocker: null,
            blockerSignature: null,
            consumerRefs: ["validation-1"],
            dependentConsumers: ["validation-1"],
            siblingBranchIds: ["branch-2"],
            successfulEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
            failedEvidenceRefs: [],
            repairNodeRefs: [],
            diagnosticOnlyNodeRefs: [],
            nextLegalTransitions: ["evaluate_downstream"],
            capabilityId: "implementation.kimi.scoped_patch",
            executorKey: "kind:implementation",
            modelRef: "moonshotai/kimi-k2.6",
            workerRef: "worker://kimi/patch",
            phase: "execute_node",
            objectiveSummary: "Patch Product/Spec wiring",
            whySelected: "Independent source edit branch.",
            currentToolId: "worker.invoke",
            currentToolInvocationRef: "runtime-tool://worker.invoke/impl-1",
            targetRefSummary: ["src/impl-1.ts"],
            readinessStatus: "executable",
            rootCauseRef: null,
            rootCauseSystemic: null,
            updatedAt: "2026-05-20T00:00:00.000Z",
            rawPromptStored: false,
            rawResponseStored: false,
            rawProviderLogStored: false,
            rawToolLogStored: false,
            rawDbRowsStored: false,
            secretsStored: false,
          },
          {
            artifactKind: "runtime_work_graph_branch_scoped_frontier_state",
            schemaVersion: "execution-platform.runtime-work-graph.branch-scoped-frontier.v1",
            graphId: "graph-1",
            currentSuperstep: 3,
            branchId: "branch-2",
            parentBranchId: null,
            nodeId: "impl-2",
            nodeKind: "implementation_scoped",
            workIntentRef: "work-intent://2",
            contractRef: "runtime-job://job-1/contract/impl-2",
            readinessRef: "runtime-job://job-1/readiness/impl-2",
            resourceRequirementRefs: ["resource-requirement://impl-2"],
            domainResourcePacketRef: null,
            resourcePacketRef: null,
            status: "blocked",
            blocker: {
              code: "resources_required",
              summary: "target snapshot missing",
              schemaPath: "nodeReadinessState.snapshotStatus",
              policyPath: null,
              reasonCodes: ["target_snapshot_missing"],
            },
            blockerSignature: "blocker-sig-2",
            consumerRefs: ["validation-2"],
            dependentConsumers: ["validation-2"],
            siblingBranchIds: ["branch-1"],
            successfulEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
            failedEvidenceRefs: [],
            repairNodeRefs: ["runtime-work-graph://node/repair-impl-2"],
            diagnosticOnlyNodeRefs: ["runtime-work-graph://node/diag-impl-2"],
            nextLegalTransitions: ["compile_node_execution_packet"],
            capabilityId: "implementation.qwen.scoped_patch",
            executorKey: "kind:implementation",
            modelRef: "qwen/qwen3-coder-next",
            workerRef: "worker://qwen/patch",
            phase: "resources_required",
            objectiveSummary: "Patch blocked branch.",
            whySelected: "Sibling branch needs materialization.",
            currentToolId: "node.compile_execution_packet",
            currentToolInvocationRef: "runtime-tool://node.compile_execution_packet/impl-2",
            targetRefSummary: ["src/impl-2.ts"],
            readinessStatus: "resources_required",
            rootCauseRef: "runtime-work-graph://frontier-root-cause/graph-1/sig-1/repeat/2",
            rootCauseSystemic: true,
            updatedAt: "2026-05-20T00:00:00.000Z",
            rawPromptStored: false,
            rawResponseStored: false,
            rawProviderLogStored: false,
            rawToolLogStored: false,
            rawDbRowsStored: false,
            secretsStored: false,
          },
        ],
        schedulerFrontierState: {
          currentSuperstep: 3,
          selectedExecutableNodeIds: ["impl-1"],
          blockedFrontierNodeIds: ["impl-2"],
          openCommitmentIds: ["C1", "C2"],
          nextLegalTransition: "execute_frontier",
        },
        schedulerModelCallEnvelope: {
          artifactKind: "runtime_work_graph_scheduler_model_call_envelope",
          schemaVersion: "execution-platform.runtime-work-graph.scheduler-model-call-envelope.v1",
          envelopeId: "graph-1:scheduler:3",
          envelopeRef: "runtime-work-graph://scheduler-model-call-envelope/graph-1%3A3",
          phase: "rejection",
          decisionSlot: "scheduler.select_next_action",
          schedulerPhase: "scheduler_decision_rejected",
          modelRef: "openai-codex/gpt-5.5",
          providerPath: "codex_app_server",
          providerProfileId: "codex_app_server",
          modelTaskClass: "global_reasoning",
          modelPolicyRef: "model-task-policy://global_reasoning/default",
          contractBoundaryId: "scheduler_global_reasoning",
          modelPolicyBindingRef: "model-contract-boundary://scheduler_global_reasoning",
          reasoningMode: "high",
          parserMode: "json_object",
          proofCleanlinessState: "clean",
          inputByteCount: 42_000,
          graphNodeCount: 12,
          graphEdgeCount: 18,
          activeFrontierCounts: {
            ready: 1,
            blocked: 1,
          },
          rejectedToolCallSummary: {
            status: "rejected",
            reasonCodes: ["target_snapshot_missing"],
          },
          schemaErrorPath: "nodeReadinessState.snapshotStatus",
          repairFieldHints: ["nodeReadinessState.snapshotStatus"],
          missingFields: ["resourcePacketRef"],
          reasonCodes: ["target_snapshot_missing"],
          rawPromptStored: false,
          rawResponseStored: false,
          rawProviderLogStored: false,
          rawToolLogStored: false,
          rawCommandLogStored: false,
          rawDbRowsStored: false,
          hiddenReasoningStored: false,
          secretsStored: false,
        },
        noProgressSignature: {
          signatureHash: "sig-1",
          terminalBlockerCode: "frontier_blocked",
          blockerReasonCodes: ["target_snapshot_missing"],
        },
        frontierRootCauseArtifact: {
          artifactKind: "runtime_work_graph_frontier_root_cause",
          signatureHash: "sig-1",
          repeatCount: 2,
          systemic: true,
          recommendedRepairBoundary: "resource_materializer_fix",
          affectedNodeIds: ["impl-2"],
          affectedBranchIds: ["branch-2"],
          successfulSiblingEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
          missingFields: ["resourcePacketRef"],
          schemaErrorPaths: ["nodeReadinessState.snapshotStatus"],
          policyErrorPaths: [],
          contractRefs: ["runtime-job://job-1/contract/impl-2"],
          domainResourcePacketKinds: ["source_edit_resource_packet"],
          providerProfileIds: [],
          nextLegalTransitions: ["compile_node_execution_packet"],
          reasonCodes: ["target_snapshot_missing"],
        },
        noProgressRepeatCount: 2,
        missionLedgerEvaluationThrottle: {
          nodeId: "impl-2",
          shouldEvaluate: false,
          reasonCodes: ["node_has_no_new_evidence"],
        },
        expansionAdmissionDecisionRef:
          "runtime-work-graph://expansion-admission/graph-1/3/admission",
        expansionAdmissionPolicyRef: "runtime-work-graph.expansion-admission.v1",
        expansionAdmissionStatus: "accepted_paged",
        expansionAdmissionOriginalNodeCount: 12,
        expansionAdmissionOriginalEdgeCount: 18,
        expansionAdmissionAdmittedNodeCount: 4,
        expansionAdmissionAdmittedEdgeCount: 6,
        expansionAdmissionDeferredNodeCount: 8,
        expansionAdmissionDeferredEdgeCount: 12,
        expansionAdmissionReadyFrontierNodeIds: ["impl-1"],
        expansionAdmissionAdmittedNodeIds: ["impl-1", "impl-2"],
        expansionAdmissionDeferredNodeIds: ["impl-3"],
        expansionAdmissionNextTransition: "persist_admitted_page",
        expansionAdmissionPrerequisiteCritical: false,
        expansionAdmissionReasonCodes: ["expansion_accepted_paged"],
        boundaryReplayCheckpointKind: "before_worker_invocation",
        boundaryReplayCheckpointRefs: [
          "runtime-job://job-1/boundary-replay/graph-1/before_worker_invocation/checkpoint-1",
        ],
        boundaryReplayGraphCheckpointRefs: [
          "runtime-work-graph://checkpoint/boundary-replay-after-resource",
        ],
        replayStartPolicy: "allowed_from_checkpoint",
        replaySafetyStatus: "safe_to_replay",
        replayFreshnessStatus: "fresh",
        replayContinuationMode: "run_node",
        nextReplayBoundary: "before_worker_invocation",
        heapPhaseSnapshots: [
          {
            snapshotRef: "heap-phase://job-1/action-gate-blocked",
            phase: "domain_action_gate_blocked",
            gateKind: "domain_action_gate_blocked",
            graphId: "graph-1",
            nodeId: "impl-2",
            heapUsedBytes: 50_000_000,
            heapTotalBytes: 100_000_000,
            rssBytes: 140_000_000,
            externalBytes: 1_000_000,
            arrayBuffersBytes: 500_000,
            graphNodeCount: 12,
            graphEdgeCount: 18,
            activeBranchCount: 2,
            largestMetadataBytes: 19_000,
            largestMetadataRef: "runtime-job://job-1/latest-run-state",
            largestArtifactBodyBytes: 120_000,
            largestArtifactBodyRef: "artifact://execution-platform/proof-source",
            latestRunStateMetadataBytes: 19_000,
            schedulerProgressMetadataBytes: 16_000,
            workQueueProjectionMetadataBytes: 12_000,
            providerRequestByteCount: 42_000,
            reasonCodes: ["heap_phase_snapshot_recorded"],
            rawPromptStored: false,
            rawResponseStored: false,
            rawProviderLogStored: false,
            rawToolLogStored: false,
            rawCommandLogStored: false,
            rawDbRowsStored: false,
            secretsStored: false,
          },
        ],
      },
      totalWallMs: 123_456,
      phaseWallClock: [{ phase: "node_local_node_resource_demand", wallMs: 1000 }],
      modelUsageByModel: [{ modelRef: "openai-codex/gpt-5.5", usageKind: "estimated" }],
      missingUsageEventCount: 1,
      usageUnavailableReasons: [{ reason: "codex_app_server_usage_not_returned", count: 1 }],
      recommendedOperatorAction: "Replay from the node-local node resource demand/write gate boundary.",
    });

    expect(state).toMatchObject({
      artifactKind: "execution_platform_latest_run_state",
      runtimeJobId: "job-1",
      process: {
        isRunning: false,
        terminalStatus: "needs_review",
        adapterTerminalStatus: "needs_review",
        retryState: "retry_scheduled",
      },
      current: {
        phase: "domain_action_gate_blocked",
        nodeId: "node-1",
        nodeKind: "implementation_scoped",
        workIntentId: "work-intent-1",
        executionIntent: "source_edit",
        evidenceMode: ["changed_file_evidence", "validation_evidence"],
        capabilityId: "implementation.kimi.scoped_patch",
        executorKey: "kind:implementation",
        workerRef: "worker://kimi/patch",
        activeToolId: "worker.invoke",
        readinessStateRef: "runtime-job://job-1/readiness/impl-1",
        readinessStatus: "ready",
        blockerSummary: "target snapshot missing",
      },
      activeFrontier: {
        state: "present",
        status: "terminal",
        graphId: "graph-1",
        selectedNodeIds: ["impl-1"],
        blockedNodeIds: ["impl-2"],
        nextTransition: "run_frontier",
        noProgress: {
          state: "present",
          repeatCount: 2,
          terminalBlockerCode: "frontier_blocked",
        },
        rootCause: {
          state: "present",
          signatureHash: "sig-1",
          recommendedRepairBoundary: "resource_materializer_fix",
          affectedNodeIds: ["impl-2"],
          successfulSiblingEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
        },
        missionLedgerEvaluationThrottle: {
          state: "present",
          nodeId: "impl-2",
          shouldEvaluate: false,
        },
      },
      canonicalReadbackGate: {
        state: "present",
        gateKind: "terminal_needs_review",
        gateStatus: "terminal",
        confidence: "canonical",
        sourceKind: "terminal_outcome",
        nodeId: "impl-2",
        branchId: "branch-2",
        contractRef: "runtime-job://job-1/contract/impl-2",
        readinessStateRef: "runtime-job://job-1/readiness/impl-2",
        schemaPath: "nodeReadinessState.snapshotStatus",
        nextLegalTransition: "compile_node_execution_packet",
        successfulSiblingEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
        rawPromptStored: false,
        rawResponseStored: false,
        rawProviderLogStored: false,
      },
      rawPromptStored: false,
      rawResponseStored: false,
      rawProviderLogStored: false,
      rawToolLogStored: false,
      rawDbRowsStored: false,
      secretsStored: false,
    });
    expect(state.proofEnvironment).toMatchObject({
      state: "present",
      largestMetadataBytes: 19_000,
      largestMetadataRef: "runtime-job://job-1/latest-run-state",
      largestArtifactBodyBytes: 120_000,
      largestArtifactBodyRef: "artifact://execution-platform/proof-source",
      latestRunStateMetadataBytes: 19_000,
      schedulerProgressMetadataBytes: 16_000,
      workQueueProjectionMetadataBytes: 12_000,
      providerRequestMaxBytes: 42_000,
      reasonCodes: ["heap_phase_snapshot_recorded"],
      rawPromptStored: false,
      rawResponseStored: false,
      rawProviderLogStored: false,
      rawToolLogStored: false,
      rawDbRowsStored: false,
      secretsStored: false,
    });
    expect(state.expansionAdmission).toMatchObject({
      state: "present",
      status: "accepted_paged",
      originalNodeCount: 12,
      admittedNodeCount: 4,
      deferredNodeCount: 8,
      nextTransition: "persist_admitted_page",
      prerequisiteCritical: false,
      readyFrontierNodeIds: ["impl-1"],
    });
    expect(state.schedulerModelCallEnvelope).toMatchObject({
      phase: "rejection",
      decisionSlot: "scheduler.select_next_action",
      schedulerPhase: "scheduler_decision_rejected",
      inputByteCount: 42_000,
      graphNodeCount: 12,
      contractBoundaryId: "scheduler_global_reasoning",
      modelPolicyBindingRef: "model-contract-boundary://scheduler_global_reasoning",
      proofCleanlinessState: "clean",
      schemaErrorPath: "nodeReadinessState.snapshotStatus",
      rawPromptStored: false,
      rawResponseStored: false,
      rawProviderLogStored: false,
      hiddenReasoningStored: false,
    });
    expect(state.boundaryReplay).toMatchObject({
      state: "present",
      latestCheckpointKind: "before_worker_invocation",
      checkpointRefs: [
        "runtime-job://job-1/boundary-replay/graph-1/before_worker_invocation/checkpoint-1",
      ],
      graphCheckpointRefs: ["runtime-work-graph://checkpoint/boundary-replay-after-resource"],
      replayStartPolicy: "allowed_from_checkpoint",
      replaySafetyStatus: "safe_to_replay",
      replayFreshnessStatus: "fresh",
      replayContinuationMode: "run_node",
      currentReplayBoundary: "before_worker_invocation",
      nextReplayBoundary: "before_worker_invocation",
    });
    expect(state.activeFrontier.branchStates).toMatchObject([
      {
        branchId: "branch-1",
        nodeId: "impl-1",
        status: "running",
        contractRef: "runtime-job://job-1/contract/impl-1",
        dependentConsumers: ["validation-1"],
      },
      {
        branchId: "branch-2",
        nodeId: "impl-2",
        status: "blocked",
        blockerSchemaPath: "nodeReadinessState.snapshotStatus",
        nextTransition: "compile_node_execution_packet",
        readinessStateRef: "runtime-job://job-1/readiness/impl-2",
        successfulEvidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
        repairNodeRefs: ["runtime-work-graph://node/repair-impl-2"],
        diagnosticOnlyNodeRefs: ["runtime-work-graph://node/diag-impl-2"],
      },
    ]);
    expect(JSON.stringify(state)).not.toContain("raw prompt");
  });

  it("keeps node-local lifecycle refs in latest-run-state and canonical gate projection", () => {
    const state = buildLatestRunState({
      runtimeJobId: "job-node-local",
      workItemId: "work-node-local",
      graphId: "graph-node-local",
      processRunning: true,
      latestProgress: {
        currentPhase: "resource_demand_blocked",
        nodeId: "impl-node-local",
        activeNodeKind: "implementation_scoped",
        workIntentId: "work-intent-node-local",
        executionIntent: "source_edit",
        evidenceMode: ["changed_file_evidence"],
        nodeResourceDemandStatus: "blocked",
        nodeResourceDemandSessionRefs: ["node-resource-demand://impl-node-local/session-1"],
        nodeResourceLedgerStatus: "ready",
        nodeResourceLedgerManifestRefs: ["node-resource-ledger://impl-node-local"],
        domainResourceSelectionStatus: "blocked",
        domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
        actionGateStatus: "blocked",
        actionGateMissingFields: ["targetFileSnapshots"],
        providerDiagnosticStatus: "available",
        providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
        branchScopedFrontierStates: [
          {
            branchId: "branch-node-local",
            nodeId: "impl-node-local",
            nodeKind: "implementation_scoped",
            workIntentRef: "work-intent://impl-node-local",
            contractRef: "contract://impl-node-local",
            readinessRef: "readiness://impl-node-local",
            resourceRequirementRefs: ["resource-requirement://impl-node-local"],
            nodeResourceDemandSessionRefs: ["node-resource-demand://impl-node-local/session-1"],
            nodeResourceDemandStatus: "blocked",
            nodeResourceLedgerManifestRefs: ["node-resource-ledger://impl-node-local"],
            nodeResourceLedgerStatus: "ready",
            domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
            domainResourceSelectionStatus: "blocked",
            actionGateStatus: "blocked",
            actionGateMissingFields: ["targetFileSnapshots"],
            providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
            providerDiagnosticStatus: "available",
            status: "blocked",
            nodeLifecycleProjectionGate: "worker_context_window_required",
            nodeLifecycleProjectionStatus: "blocked",
            phase: "worker_context_window_required",
            blocker: {
              code: "resource_demand_blocked",
              summary: "node needs scoped context window",
              schemaPath: "nodeResourceDemandSession.selectedWindowRefs",
              reasonCodes: ["node_resource_demand_scope_missing"],
            },
            nextLegalTransitions: ["fulfill_node_resource_demand"],
          },
        ],
      },
    });

    expect(state.current).toMatchObject({
      nodeResourceDemandSessionRefs: ["node-resource-demand://impl-node-local/session-1"],
      nodeResourceDemandStatus: "blocked",
      nodeResourceLedgerManifestRefs: ["node-resource-ledger://impl-node-local"],
      nodeResourceLedgerStatus: "ready",
      domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
      domainResourceSelectionStatus: "blocked",
      actionGateStatus: "blocked",
      actionGateMissingFields: ["targetFileSnapshots"],
      providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
      providerDiagnosticStatus: "available",
    });
    expect(state.activeFrontier.branchStates[0]).toMatchObject({
      branchId: "branch-node-local",
      nodeResourceDemandSessionRefs: ["node-resource-demand://impl-node-local/session-1"],
      nodeResourceLedgerManifestRefs: ["node-resource-ledger://impl-node-local"],
      domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
      actionGateStatus: "blocked",
      providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
    });
    expect(state.canonicalReadbackGate).toMatchObject({
      gateKind: "worker_context_window_required",
      sourceKind: "branch_scoped_frontier",
      nodeResourceDemandSessionRefs: ["node-resource-demand://impl-node-local/session-1"],
      nodeResourceLedgerManifestRefs: ["node-resource-ledger://impl-node-local"],
      domainResourceSelectionRefs: ["domain-resource-selection://impl-node-local/1"],
      actionGateStatus: "blocked",
      providerDiagnosticRefs: ["provider-diagnostic://impl-node-local/qwen"],
    });
    expect(JSON.stringify(state)).not.toContain("raw prompt");
  });
});
