import { describe, expect, it } from "vitest";
import { buildLatestRunState } from "./latest-run-state.ts";

describe("latest run state", () => {
  it("builds a compact compaction-safe operator state without raw storage", () => {
    const state = buildLatestRunState({
      runtimeJobId: "job-1",
      workItemId: "work-1",
      promptHash: "sha256:prompt",
      promptRef: "source-prompt://prompt",
      promptLength: 12_345,
      processRunning: false,
      terminalStatus: "needs_review",
      adapterTerminalStatus: "needs_review",
      retryState: "retry_scheduled",
      runtimeJob: {
        state: "pending",
        attempts: 1,
        maxAttempts: 2,
        workerId: null,
        startedAt: "2026-05-20T00:00:00.000Z",
        completedAt: null,
      },
      graphId: "graph-1",
      latestProgress: {
        stage: "context_synthesis_group_expansion",
        currentPhase: "group_guidance_missing",
        schedulerPhase: "context_synthesis_repair_needed",
        nodeId: "node-1",
        roleId: "context_synthesis",
        modelRef: "openai-codex/gpt-5.5",
        providerPath: "codex_app_server",
        currentObjective: "Repair group guidance.",
        blockerSummary: "groupPlanningGuidance missing",
        nextDecisionNeeded: "focused_repair",
        eli5Progress: "OpenClaw needs a field repair before implementation.",
        reasonCodes: ["context_synthesis_group_planning_guidance_missing"],
        artifactRefs: ["runtime-job://job-1/context-synthesis/input-manifest/ref"],
        parallelFrontier: {
          currentSuperstep: 3,
          selectedNodeIds: ["impl-1"],
          runningNodeIds: ["impl-1"],
          blockedNodeIds: ["impl-2"],
          branchResults: [
            {
              branchId: "branch-1",
              nodeId: "impl-1",
              nodeKind: "implementation_scoped",
              capabilityId: "implementation.kimi.scoped_patch",
              targetCommitmentIds: ["C1"],
              status: "running",
              evidenceRefs: ["runtime-job://job-1/node/impl-1/evidence"],
              nextTransition: "evaluate_downstream",
              reasonCodes: ["frontier_node_running"],
            },
            {
              branchId: "branch-2",
              nodeId: "impl-2",
              nodeKind: "implementation_scoped",
              capabilityId: "implementation.qwen.scoped_patch",
              targetCommitmentIds: ["C2"],
              status: "blocked",
              failureClass: "resource_materialization",
              errorPath: "nodeReadinessState.snapshotStatus",
              blockerSummary: "target snapshot missing",
              repairAction: "materialize_target_snapshot",
              nextTransition: "materialize_resources_or_split_task",
              readinessStateRef: "runtime-job://job-1/readiness/impl-2",
              reasonCodes: ["target_snapshot_missing"],
            },
          ],
        },
        schedulerFrontierState: {
          currentSuperstep: 3,
          selectedExecutableNodeIds: ["impl-1"],
          blockedFrontierNodeIds: ["impl-2"],
          openCommitmentIds: ["C1", "C2"],
          nextLegalTransition: "execute_frontier",
        },
        noProgressSignature: {
          signatureHash: "sig-1",
          terminalBlockerCode: "frontier_blocked",
          blockerReasonCodes: ["target_snapshot_missing"],
        },
        noProgressRepeatCount: 2,
        missionLedgerEvaluationThrottle: {
          nodeId: "impl-2",
          shouldEvaluate: false,
          reasonCodes: ["node_has_no_new_evidence"],
        },
        expansionAdmissionDecisionRef:
          "runtime-work-graph://expansion-admission/graph-1/3/admission",
        expansionAdmissionPolicyRef: "runtime-work-graph.expansion-admission.v1",
        expansionAdmissionStatus: "accepted_paged",
        expansionAdmissionOriginalNodeCount: 12,
        expansionAdmissionOriginalEdgeCount: 18,
        expansionAdmissionAdmittedNodeCount: 4,
        expansionAdmissionAdmittedEdgeCount: 6,
        expansionAdmissionDeferredNodeCount: 8,
        expansionAdmissionDeferredEdgeCount: 12,
        expansionAdmissionReadyFrontierNodeIds: ["impl-1"],
        expansionAdmissionAdmittedNodeIds: ["impl-1", "impl-2"],
        expansionAdmissionDeferredNodeIds: ["impl-3"],
        expansionAdmissionNextTransition: "persist_admitted_page",
        expansionAdmissionPrerequisiteCritical: false,
        expansionAdmissionReasonCodes: ["expansion_accepted_paged"],
        boundaryReplayCheckpointKind: "after_resource_materialization",
        boundaryReplayCheckpointRefs: [
          "runtime-job://job-1/boundary-replay/graph-1/after_resource_materialization/checkpoint-1",
        ],
        boundaryReplayGraphCheckpointRefs: [
          "runtime-work-graph://checkpoint/boundary-replay-after-resource",
        ],
        replayStartPolicy: "allowed_from_checkpoint",
        replaySafetyStatus: "safe_to_replay",
        replayFreshnessStatus: "fresh",
        replayContinuationMode: "run_node",
        nextReplayBoundary: "before_worker_invocation",
      },
      totalWallMs: 123_456,
      phaseWallClock: [{ phase: "context_synthesis", wallMs: 1000 }],
      modelUsageByModel: [{ modelRef: "openai-codex/gpt-5.5", usageKind: "estimated" }],
      missingUsageEventCount: 1,
      usageUnavailableReasons: [{ reason: "codex_app_server_usage_not_returned", count: 1 }],
      recommendedOperatorAction: "Replay from context synthesis after repair.",
    });

    expect(state).toMatchObject({
      artifactKind: "execution_platform_latest_run_state",
      runtimeJobId: "job-1",
      process: {
        isRunning: false,
        terminalStatus: "needs_review",
        adapterTerminalStatus: "needs_review",
        retryState: "retry_scheduled",
      },
      current: {
        phase: "group_guidance_missing",
        nodeId: "node-1",
        blockerSummary: "groupPlanningGuidance missing",
      },
      activeFrontier: {
        state: "present",
        status: "terminal",
        graphId: "graph-1",
        selectedNodeIds: ["impl-1"],
        blockedNodeIds: ["impl-2"],
        nextTransition: "run_frontier",
        noProgress: {
          state: "present",
          repeatCount: 2,
          terminalBlockerCode: "frontier_blocked",
        },
        missionLedgerEvaluationThrottle: {
          state: "present",
          nodeId: "impl-2",
          shouldEvaluate: false,
        },
      },
      rawPromptStored: false,
      rawResponseStored: false,
      rawProviderLogStored: false,
      rawToolLogStored: false,
      rawDbRowsStored: false,
      secretsStored: false,
    });
    expect(state.expansionAdmission).toMatchObject({
      state: "present",
      status: "accepted_paged",
      originalNodeCount: 12,
      admittedNodeCount: 4,
      deferredNodeCount: 8,
      nextTransition: "persist_admitted_page",
      prerequisiteCritical: false,
      readyFrontierNodeIds: ["impl-1"],
    });
    expect(state.boundaryReplay).toMatchObject({
      state: "present",
      latestCheckpointKind: "after_resource_materialization",
      checkpointRefs: [
        "runtime-job://job-1/boundary-replay/graph-1/after_resource_materialization/checkpoint-1",
      ],
      graphCheckpointRefs: ["runtime-work-graph://checkpoint/boundary-replay-after-resource"],
      replayStartPolicy: "allowed_from_checkpoint",
      replaySafetyStatus: "safe_to_replay",
      replayFreshnessStatus: "fresh",
      replayContinuationMode: "run_node",
      currentReplayBoundary: "after_resource_materialization",
      nextReplayBoundary: "before_worker_invocation",
    });
    expect(state.activeFrontier.branchStates).toMatchObject([
      {
        branchId: "branch-1",
        nodeId: "impl-1",
        status: "running",
      },
      {
        branchId: "branch-2",
        nodeId: "impl-2",
        status: "blocked",
        errorPath: "nodeReadinessState.snapshotStatus",
        nextTransition: "materialize_resources_or_split_task",
        readinessStateRef: "runtime-job://job-1/readiness/impl-2",
      },
    ]);
    expect(JSON.stringify(state)).not.toContain("raw prompt");
  });
});
