import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { embedReleaseManifest } from "../../scripts/generate-release-manifest.mjs";
import { releaseManifestDigest } from "../../scripts/lib/release-manifest.mjs";
import { createReleaseManifestFixture } from "../helpers/release-manifest-fixture.js";

const tempDirs: string[] = [];

afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

function makeStagedPackage(): string {
  const packageRoot = fs.mkdtempSync(path.join(os.tmpdir(), "openclaw-release-generate-"));
  tempDirs.push(packageRoot);
  fs.writeFileSync(
    path.join(packageRoot, "package.json"),
    `${JSON.stringify(
      {
        name: "openclaw",
        version: "2026.7.19-b1.1",
        files: ["dist/", "release-manifest.json"],
        openclaw: {
          release: {
            packageShape: "prototype-b-native-release-set-v1",
            manifestPath: "release-manifest.json",
          },
        },
      },
      null,
      2,
    )}\n`,
  );
  return packageRoot;
}

describe("generate release manifest", () => {
  it("writes deterministic bytes and binds their digest in staged package metadata", async () => {
    const packageRoot = makeStagedPackage();
    const manifest = createReleaseManifestFixture();
    const first = await embedReleaseManifest({ packageRoot, manifest });
    const firstBytes = fs.readFileSync(path.join(packageRoot, "release-manifest.json"));
    const second = await embedReleaseManifest({ packageRoot, manifest });
    const secondBytes = fs.readFileSync(path.join(packageRoot, "release-manifest.json"));
    const packageJson = JSON.parse(fs.readFileSync(path.join(packageRoot, "package.json"), "utf8"));

    expect(first).toEqual(second);
    expect(firstBytes.equals(secondBytes)).toBe(true);
    expect(first.releaseManifestDigest).toBe(releaseManifestDigest(firstBytes));
    expect(packageJson.openclaw.release).toMatchObject({
      packageShape: "prototype-b-native-release-set-v1",
      manifestPath: "release-manifest.json",
      manifestSha256: first.releaseManifestDigest,
    });
    await expect(embedReleaseManifest({ packageRoot, manifest, check: true })).resolves.toEqual(
      first,
    );
  });

  it("rejects package version drift and check-mode byte drift", async () => {
    const packageRoot = makeStagedPackage();
    const manifest = createReleaseManifestFixture();
    await embedReleaseManifest({ packageRoot, manifest });
    fs.appendFileSync(path.join(packageRoot, "release-manifest.json"), "\n");
    await expect(embedReleaseManifest({ packageRoot, manifest, check: true })).rejects.toThrow(
      "does not match generated bytes",
    );

    const wrongVersionRoot = makeStagedPackage();
    const wrongVersion = createReleaseManifestFixture();
    wrongVersion.package.version = "2026.7.19-b1.2";
    wrongVersion.artifacts[0]!.packageVersion = "2026.7.19-b1.2";
    await expect(
      embedReleaseManifest({ packageRoot: wrongVersionRoot, manifest: wrongVersion }),
    ).rejects.toThrow("staged package version mismatch");
  });
});
